services:
  api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: iris-ml-api
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_RELOAD=false
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - MODEL_PATH=models/iris_classifier.joblib
      - MODEL_VERSION=v1.0.0
      - ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
    volumes:
      # Mount models directory for persistence (optional)
      - ../models:/app/models
      # Mount logs directory (optional)
      - ../logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - iris-network

networks:
  iris-network:
    driver: bridge

volumes:
  models_data:
  logs_data: