services:
  - type: web
    name: iris-ml-pipeline-api
    runtime: docker
    repo: https://github.com/yourusername/iris-ml-pipeline
    dockerfilePath: ./deployment/Dockerfile
    dockerContext: .
    envVars:
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health